/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#3f001b",
        "surface-dim": "var(--muted)",
        "outline-variant": "var(--border)",
        "surface-variant": "var(--secondary)",
        "secondary-container": "var(--accent)",
        "surface-container-lowest": "var(--popover)",
        "secondary": "var(--secondary)",
        "inverse-surface": "var(--foreground)",
        "error": "var(--destructive)",
        "primary-fixed": "var(--accent)",
        "secondary-fixed": "var(--secondary)",
        "inverse-on-surface": "var(--background)",
        "on-tertiary-fixed-variant": "#574500",
        "on-primary": "var(--primary-foreground)",
        "inverse-primary": "var(--primary)",
        "on-primary-fixed": "var(--primary)",
        "tertiary-container": "#cca730",
        "on-error": "var(--destructive-foreground)",
        "on-secondary-container": "var(--secondary-foreground)",
        "secondary-fixed-dim": "var(--secondary)",
        "error-container": "var(--destructive)",
        "surface": "var(--card)",
        "on-surface": "var(--card-foreground)",
        "on-secondary": "var(--secondary-foreground)",
        "on-secondary-fixed-variant": "var(--secondary-foreground)",
        "on-primary-container": "var(--primary-foreground)",
        "surface-container-high": "var(--input)",
        "on-primary-fixed-variant": "var(--primary)",
        "tertiary-fixed": "#ffe088",
        "tertiary-fixed-dim": "#e9c349",
        "tertiary": "#735c00",
        "on-tertiary": "#ffffff",
        "background": "var(--background)",
        "primary": "var(--primary)",
        "surface-container-low": "var(--muted)",
        "primary-fixed-dim": "var(--primary)",
        "outline": "var(--border)",
        "on-error-container": "var(--destructive-foreground)",
        "primary-container": "var(--accent)",
        "surface-tint": "var(--ring)",
        "on-surface-variant": "var(--muted-foreground)",
        "on-tertiary-container": "#4f3d00",
        "surface-bright": "var(--background)",
        "surface-container-highest": "var(--border)",
        "on-tertiary-fixed": "#241a00",
        "surface-container": "var(--secondary)",
        "on-background": "var(--foreground)",
        "gold": "#D4AF37",
        
        card: "var(--card)",
        ring: "var(--ring)",
        input: "var(--input)",
        muted: "var(--muted)",
        accent: "var(--accent)",
        border: "var(--border)",
        popover: "var(--popover)",
        sidebar: "var(--sidebar)",
        foreground: "var(--foreground)",
        destructive: "var(--destructive)",
        "sidebar-ring": "var(--sidebar-ring)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-border": "var(--sidebar-border)",
        "card-foreground": "var(--card-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "muted-foreground": "var(--muted-foreground)",
        "accent-foreground": "var(--accent-foreground)",
        "popover-foreground": "var(--popover-foreground)",
        "primary-foreground": "var(--primary-foreground)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "secondary-foreground": "var(--secondary-foreground)",
        "destructive-foreground": "var(--destructive-foreground)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "muted-2": "var(--muted-2)",
        "muted-2-foreground": "var(--muted-2-foreground)",
        "gradient-1": "var(--gradient-1)",
        "gradient-2": "var(--gradient-2)",
        "gradient-3": "var(--gradient-3)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "xs":   "4px",
        "sm":   "12px",
        "base": "8px",
        "md":   "24px",
        "lg":   "48px",
        "xl":   "80px",
        "gutter": "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-xl":       ["Playfair Display", "serif"],
        "headline-lg":       ["Playfair Display", "serif"],
        "headline-md":       ["Playfair Display", "serif"],
        "display-lg":        ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-lg":           ["Inter", "sans-serif"],
        "body-md":           ["Inter", "sans-serif"],
        "body-sm":           ["Inter", "sans-serif"],
        "label-caps":        ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl":       ["48px", { lineHeight: "56px",  fontWeight: "600" }],
        "headline-lg":       ["32px", { lineHeight: "40px",  fontWeight: "600" }],
        "headline-md":       ["24px", { lineHeight: "32px",  fontWeight: "500" }],
        "display-lg":        ["64px", { lineHeight: "72px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px",  letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg":           ["18px", { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":           ["16px", { lineHeight: "24px",  fontWeight: "400" }],
        "body-sm":           ["14px", { lineHeight: "20px",  fontWeight: "400" }],
        "label-caps":        ["12px", { lineHeight: "16px",  letterSpacing: "0.1em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
      keyframes: {
        fadeIn: {
          "0%":   { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%":   { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition:  "200% 0" },
        },
        "pulse-gold": {
          "0%, 100%": { filter: "drop-shadow(0 0 5px rgba(212,175,55,0.3))" },
          "50%":      { filter: "drop-shadow(0 0 20px rgba(212,175,55,0.6))" },
        },
        "monogram-draw": {
          "0%":   { strokeDashoffset: "1000", opacity: "0" },
          "50%":  { opacity: "1" },
          "100%": { strokeDashoffset: "0" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "border-beam": {
          "100%": {
            "offset-distance": "100%",
          },
        },
        "fade-in-out": {
          "0%": { opacity: "0" },
          "20%": { opacity: "1" },
          "80%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        progress: {
          from: { width: "0%" },
          to: { width: "100%" },
        },
        infiniteSlider: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(calc(-250px * 5))" },
        },
        infiniteSliderReverse: {
          "0%": { transform: "translateX(calc(-250px * 5))" },
          "100%": { transform: "translateX(0)" },
        },
        "fade-in-scale": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        transform1: {
          "0%, 25%, 100%": { width: "100%", paddingBottom: "120%" },
          "33.33%, 58.33%": { width: "0%", paddingBottom: "0%" },
          "66.66%, 91.66%": { width: "90%", paddingBottom: "100%" },
        },
        transform2: {
          "0%, 25%, 100%": { width: "65%", paddingBottom: "65%" },
          "33.33%, 58.33%": { width: "95%", paddingBottom: "114%" },
          "66.66%, 91.66%": { width: "52%", paddingBottom: "52%" },
        },
        transform3: {
          "0%, 25%, 100%": { width: "78%", paddingBottom: "100%" },
          "33.33%, 58.33%": { width: "78%", paddingBottom: "94%" },
          "66.66%, 91.66%": { width: "95%", paddingBottom: "76%" },
        },
        transform4: {
          "0%, 25%, 66.66%, 91.66%, 100%": { width: "0%", paddingBottom: "0%" },
          "33.33%, 58.33%": { width: "65%", paddingBottom: "46%" },
        },
        image1: {
          "0%, 25%, 100%": { opacity: "1" },
          "33.33%, 58.33%, 66.66%, 91.66%": { opacity: "0" },
        },
        image2: {
          "0%, 25%, 33.33%, 58.33%, 100%": { opacity: "0" },
          "66.66%, 91.66%": { opacity: "1" },
        },
        image3: {
          "0%, 25%, 66.66%, 91.66%, 100%": { opacity: "0" },
          "33.33%, 58.33%": { opacity: "1" },
        },
        "gradient-spin": {
          "0%": { transform: "translateX(-50%) translateY(-50%) rotate(0deg)" },
          "100%": { transform: "translateX(-50%) translateY(-50%) rotate(360deg)" },
        },
        "shadow-ping": {
          "0%": { boxShadow: "0 0 0 0px var(--neutral-100)" },
          "50%": { boxShadow: "0 0 0 12px var(--neutral-300)" },
          "100%": { boxShadow: "0 0 0 12px transparent" },
        },
        "show-text": {
          "0%, 14.28%": { opacity: "0" },
          "17%, 26%": { opacity: "1" },
          "28.58%, 100%": { opacity: "0" },
        },
        "flip-btn": {
          to: { transform: "rotate(360deg)" },
        },
        "rotate-btn": {
          to: { transform: "rotate(90deg)" },
        },
        "slide-to-right": {
          "0%": { opacity: "0", left: "0" },
          "50%": { opacity: "1" },
          "100%": { opacity: "0", left: "80%" },
        },
        "slide-to-top": {
          "0%": { opacity: "0", bottom: "0" },
          "50%": { opacity: "1" },
          "100%": { opacity: "0", bottom: "80%" },
        },
        "light-to-right": {
          "0%": { transform: "translate(0%)", opacity: "0" },
          "50%": { opacity: "1" },
          "100%": { transform: "translate(100%)", opacity: "0" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        "fade-in-v4": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "shimmer-slide": {
          to: { transform: "translate(calc(100cqw - 100%), 0)" },
        },
        "spin-around": {
          "0%": { transform: "translateZ(0) rotate(0)" },
          "15%, 35%": { transform: "translateZ(0) rotate(90deg)" },
          "65%, 85%": { transform: "translateZ(0) rotate(270deg)" },
          "100%": { transform: "translateZ(0) rotate(360deg)" },
        },
        shine: {
          "0%": { backgroundPosition: "0% 0%" },
          "50%": { backgroundPosition: "100% 100%" },
          to: { backgroundPosition: "0% 0%" },
        },
      },
      animation: {
        fadeIn:         "fadeIn 1.5s ease-out forwards",
        shimmer:        "shimmer 8s infinite linear",
        "pulse-gold":   "pulse-gold 3s infinite ease-in-out",
        "monogram-draw":"monogram-draw 4s cubic-bezier(.4,0,.2,1) forwards",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "border-beam": "border-beam calc(var(--duration)*1s) infinite linear",
        "fade-in-out": "fade-in-out 4s ease-in-out",
        "fade-in": "fade-in-v4 0.7s ease-out forwards",
        "progress": "progress 8s linear",
        "infinite-slider": "infiniteSlider 20s linear infinite",
        "infinite-slider-reverse": "infiniteSliderReverse 20s linear infinite",
        "shadow-ping": "shadow-ping 1.5s ease-in-out infinite",
        "flip-btn": "flip-btn 6s infinite steps(2, end)",
        "rotate-btn": "rotate-btn 3s linear infinite both",
        "light-to-right-top": "light-to-right 4s linear infinite",
        "light-to-right-bottom": "light-to-right 4s linear infinite",
        "marquee": "marquee 25s linear infinite",
        "slide-to-right": "slide-to-right 3s linear infinite",
        "slide-to-top": "slide-to-top 3s linear infinite",
        "shimmer-slide": "shimmer-slide var(--speed) ease-in-out infinite alternate",
        "spin-around": "spin-around calc(var(--speed) * 2) infinite linear",
        "shine": "shine var(--duration) infinite linear",
      },
    },
  },
  plugins: [],
}
