/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#3f001b",
        "surface-dim": "var(--muted)",
        "outline-variant": "var(--border)",
        "surface-variant": "var(--secondary)",
        "secondary-container": "var(--accent)",
        "surface-container-lowest": "var(--popover)",
        "secondary": "var(--secondary)",
        "inverse-surface": "var(--foreground)",
        "error": "var(--destructive)",
        "primary-fixed": "var(--accent)",
        "secondary-fixed": "var(--secondary)",
        "inverse-on-surface": "var(--background)",
        "on-tertiary-fixed-variant": "#574500",
        "on-primary": "var(--primary-foreground)",
        "inverse-primary": "var(--primary)",
        "on-primary-fixed": "var(--primary)",
        "tertiary-container": "#cca730",
        "on-error": "var(--destructive-foreground)",
        "on-secondary-container": "var(--secondary-foreground)",
        "secondary-fixed-dim": "var(--secondary)",
        "error-container": "var(--destructive)",
        "surface": "var(--card)",
        "on-surface": "var(--card-foreground)",
        "on-secondary": "var(--secondary-foreground)",
        "on-secondary-fixed-variant": "var(--secondary-foreground)",
        "on-primary-container": "var(--primary-foreground)",
        "surface-container-high": "var(--input)",
        "on-primary-fixed-variant": "var(--primary)",
        "tertiary-fixed": "#ffe088",
        "tertiary-fixed-dim": "#e9c349",
        "tertiary": "#735c00",
        "on-tertiary": "#ffffff",
        "background": "var(--background)",
        "primary": "var(--primary)",
        "surface-container-low": "var(--muted)",
        "primary-fixed-dim": "var(--primary)",
        "outline": "var(--border)",
        "on-error-container": "var(--destructive-foreground)",
        "primary-container": "var(--accent)",
        "surface-tint": "var(--ring)",
        "on-surface-variant": "var(--muted-foreground)",
        "on-tertiary-container": "#4f3d00",
        "surface-bright": "var(--background)",
        "surface-container-highest": "var(--border)",
        "on-tertiary-fixed": "#241a00",
        "surface-container": "var(--secondary)",
        "on-background": "var(--foreground)",
        "gold": "#D4AF37",
        
        card: "var(--card)",
        ring: "var(--ring)",
        input: "var(--input)",
        muted: "var(--muted)",
        accent: "var(--accent)",
        border: "var(--border)",
        popover: "var(--popover)",
        sidebar: "var(--sidebar)",
        foreground: "var(--foreground)",
        destructive: "var(--destructive)",
        "sidebar-ring": "var(--sidebar-ring)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-border": "var(--sidebar-border)",
        "card-foreground": "var(--card-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "muted-foreground": "var(--muted-foreground)",
        "accent-foreground": "var(--accent-foreground)",
        "popover-foreground": "var(--popover-foreground)",
        "primary-foreground": "var(--primary-foreground)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "secondary-foreground": "var(--secondary-foreground)",
        "destructive-foreground": "var(--destructive-foreground)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "xs":   "4px",
        "sm":   "12px",
        "base": "8px",
        "md":   "24px",
        "lg":   "48px",
        "xl":   "80px",
        "gutter": "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-xl":       ["Playfair Display", "serif"],
        "headline-lg":       ["Playfair Display", "serif"],
        "headline-md":       ["Playfair Display", "serif"],
        "display-lg":        ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-lg":           ["Inter", "sans-serif"],
        "body-md":           ["Inter", "sans-serif"],
        "body-sm":           ["Inter", "sans-serif"],
        "label-caps":        ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl":       ["48px", { lineHeight: "56px",  fontWeight: "600" }],
        "headline-lg":       ["32px", { lineHeight: "40px",  fontWeight: "600" }],
        "headline-md":       ["24px", { lineHeight: "32px",  fontWeight: "500" }],
        "display-lg":        ["64px", { lineHeight: "72px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px",  letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg":           ["18px", { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":           ["16px", { lineHeight: "24px",  fontWeight: "400" }],
        "body-sm":           ["14px", { lineHeight: "20px",  fontWeight: "400" }],
        "label-caps":        ["12px", { lineHeight: "16px",  letterSpacing: "0.1em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
      keyframes: {
        fadeIn: {
          "0%":   { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%":   { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition:  "200% 0" },
        },
        "pulse-gold": {
          "0%, 100%": { filter: "drop-shadow(0 0 5px rgba(212,175,55,0.3))" },
          "50%":      { filter: "drop-shadow(0 0 20px rgba(212,175,55,0.6))" },
        },
        "monogram-draw": {
          "0%":   { strokeDashoffset: "1000", opacity: "0" },
          "50%":  { opacity: "1" },
          "100%": { strokeDashoffset: "0" },
        },
      },
      animation: {
        fadeIn:         "fadeIn 1.5s ease-out forwards",
        shimmer:        "shimmer 8s infinite linear",
        "pulse-gold":   "pulse-gold 3s infinite ease-in-out",
        "monogram-draw":"monogram-draw 4s cubic-bezier(.4,0,.2,1) forwards",
      },
    },
  },
  plugins: [],
}
